import {renderFrame} from './engine.mjs';
import {validateSpec,totalDuration,timeline,sceneAt} from './schema.mjs';
import {cueTimeline} from './cues.mjs';

const COPY={
  es:{play:'Reproducir',pause:'Pausar',prev:'Anterior',next:'Siguiente',time:'Tiempo de reproducción',cueprev:'Frase anterior',cuenext:'Frase siguiente',alltext:'Ver todo el texto',details:'Leer la explicación y las fuentes',canvasSuffix:'Animación explicativa; la transcripción completa está debajo.',loadError:'No se ha podido cargar la especificación.',source:'Fuente',reduced:'Movimiento reducido: usa Anterior y Siguiente para explorar los estados finales.',clock:'Texto y diagrama comparten el mismo reloj.'},
  en:{play:'Play',pause:'Pause',prev:'Previous',next:'Next',time:'Playback time',cueprev:'Previous sentence',cuenext:'Next sentence',alltext:'Show all text',details:'Read the explanation and sources',canvasSuffix:'Explanatory animation; the complete transcript is below.',loadError:'The specification could not be loaded.',source:'Source',reduced:'Reduced motion: use Previous and Next to explore the final states.',clock:'Text and diagram share the same clock.'}
};

/** Accessible deterministic web player. Browser and MP4 renderer use the same renderFrame clock. */
export class S5Motion extends HTMLElement {
  constructor(){super();this.attachShadow({mode:'open'});this._time=0;this._playing=false;this._raf=0;this._allText=false;this.locale='es';}
  copy(){return COPY[this.locale]||COPY.es;}
  connectedCallback(){
    if(this._mounted)return;this._mounted=true;this._abort=new AbortController();
    this.shadowRoot.innerHTML=`<style>:host{display:block;color:#171b1b;font-family:Inter,system-ui,sans-serif;max-width:100%}canvas{width:100%;height:auto;display:block;background:#fcfbf8;border:1px solid #d4dad7;box-sizing:border-box}.controls{display:flex;align-items:center;flex-wrap:wrap;gap:10px;padding:14px 0}button{font:inherit;font-size:14px;border:1px solid #bac8c4;background:#fff;color:#171b1b;padding:9px 13px;border-radius:5px;cursor:pointer;min-height:40px}button:focus-visible,input:focus-visible{outline:3px solid var(--accent-text,#00776f);outline-offset:3px}.play{background:var(--accent-text,#00776f);color:#fff;border-color:var(--accent-text,#00776f)}input{flex:1;min-width:110px;accent-color:var(--accent-text,#00776f)}output{font-variant-numeric:tabular-nums;font-size:13px}.notice{color:#586362;font-size:13px}details{border-top:1px solid #d4dad7;padding:14px 0;line-height:1.6}article{max-width:72ch}a{color:var(--accent-text,#00776f)}</style><canvas role="img"></canvas><div class="controls"><button class="play" type="button"></button><button class="prev" type="button"></button><button class="next" type="button"></button><input type="range" min="0" max="1" step=".05" value="0"><output aria-live="off">0:00</output><button class="cueprev" type="button"></button><button class="cuenext" type="button"></button><button class="alltext" type="button" aria-pressed="false"></button></div><p class="notice" aria-live="polite"></p><details><summary></summary><article></article></details>`;
    const $=q=>this.shadowRoot.querySelector(q),opts={signal:this._abort.signal};this.canvas=$('canvas');this.range=$('input');this.output=$('output');this.button=$('.play');this.notice=$('.notice');
    this.button.addEventListener('click',()=>this._playing?this.pause():this.play(),opts);$('.prev').addEventListener('click',()=>this.step(-1),opts);$('.next').addEventListener('click',()=>this.step(1),opts);$('.cueprev').addEventListener('click',()=>this.stepCue(-1),opts);$('.cuenext').addEventListener('click',()=>this.stepCue(1),opts);$('.alltext').addEventListener('click',()=>{this._allText=!this._allText;$('.alltext').setAttribute('aria-pressed',String(this._allText));this.draw();},opts);this.range.addEventListener('input',()=>{this.pause();this.seek(Number(this.range.value));},opts);
    this._reduced=matchMedia('(prefers-reduced-motion: reduce)');this._reduced.addEventListener('change',()=>{this.pause();this.draw();},opts);this._resize=new ResizeObserver(()=>this.draw());this._resize.observe(this);this.localizeControls();if(this.getAttribute('src'))this.load().catch(e=>this.notice.textContent=e.message);
  }
  disconnectedCallback(){this.pause();this._abort?.abort();this._resize?.disconnect();this._mounted=false;}
  localizeControls(){if(!this.shadowRoot)return;const c=this.copy(),$=q=>this.shadowRoot.querySelector(q);$('.play').textContent=this._playing?c.pause:c.play;$('.prev').textContent=c.prev;$('.next').textContent=c.next;this.range?.setAttribute('aria-label',c.time);$('.cueprev').textContent=c.cueprev;$('.cuenext').textContent=c.cuenext;$('.alltext').textContent=c.alltext;$('summary').textContent=c.details;}
  async load(){const src=this.getAttribute('src'),themeSrc=this.getAttribute('theme-src')||new URL('../theme/5sigmas.json',import.meta.url).href,[a,b]=await Promise.all([fetch(src,{signal:this._abort.signal}),fetch(themeSrc,{signal:this._abort.signal})]);if(!a.ok||!b.ok)throw new Error(this.copy().loadError);this.configure(await a.json(),await b.json());}
  configure(spec,theme){this.pause();validateSpec(spec);this.spec=structuredClone(spec);this.theme=structuredClone(theme);this.locale=spec.locale==='en'?'en':'es';this.duration=totalDuration(spec);this._time=0;this.style.setProperty('--accent-text',spec.visualIdentity?.accentText||theme.accentText||'#00776F');this.setAttribute('lang',this.locale);this.localizeControls();const c=this.copy();this.canvas.setAttribute('aria-label',spec.title+'. '+c.canvasSuffix);this.range.max=String(this.duration);const article=this.shadowRoot.querySelector('article');article.replaceChildren();for(const scene of spec.scenes){const h=document.createElement('h3');h.textContent=scene.title.join(' ');article.append(h);for(const text of scene.paragraphs){const p=document.createElement('p');p.textContent=text;article.append(p);}for(const [i,url] of (scene.evidence.urls||[]).entries()){const a=document.createElement('a');a.href=url;a.rel='noopener noreferrer';a.target='_blank';a.textContent=`${c.source} ${i+1} · ${new URL(url).hostname}`;article.append(a,document.createElement('br'));}}this.seek(.6);}
  seek(seconds){if(!this.spec)return;this._time=Math.max(0,Math.min(this.duration-.001,Number(seconds)||0));if(this._playing){this._clock=performance.now();this._base=this._time;}this.draw();}
  step(delta){if(!this.spec)return;this.pause();const i=sceneAt(this.spec,this._time).index+delta,item=timeline(this.spec)[Math.max(0,Math.min(this.spec.scenes.length-1,i))];this.seek(item.start+.6);}
  stepCue(delta){if(!this.spec)return;this.pause();const rows=cueTimeline(this.spec);if(!rows.length)return;let i=rows.findIndex(c=>this._time>=c.at&&this._time<c.end);if(i<0){const later=rows.findIndex(c=>c.at>this._time);i=later<0?rows.length-1:(delta>0?later:later-1);}else i+=delta;this.seek(rows[Math.max(0,Math.min(rows.length-1,i))].at+.3);}
  play(){if(!this.spec||this._playing||this._reduced?.matches)return;if(this._time>=this.duration-.05)this._time=0;this._playing=true;this.button.textContent=this.copy().pause;this._clock=performance.now();this._base=this._time;const tick=now=>{if(!this._playing)return;this._time=Math.min(this.duration-.001,this._base+(now-this._clock)/1000);this.draw();if(this._time>=this.duration-.01)return this.pause();this._raf=requestAnimationFrame(tick);};this._raf=requestAnimationFrame(tick);}
  pause(){this._playing=false;cancelAnimationFrame(this._raf);if(this.button)this.button.textContent=this.copy().play;}
  draw(){if(!this.spec||!this.canvas)return;const reduced=this._reduced?.matches||false;this.lastFrame=renderFrame(this.canvas,this.spec,this._time,this.theme,{portrait:this.clientWidth<720,reducedMotion:reduced,allText:this._allText});this.range.value=String(this._time);this.output.textContent=`${Math.floor(this._time/60)}:${String(Math.floor(this._time%60)).padStart(2,'0')}`;this.button.disabled=reduced;this.notice.textContent=reduced?this.copy().reduced:this.copy().clock;}
}
if(!customElements.get('s5-motion'))customElements.define('s5-motion',S5Motion);
