const clamp=v=>Math.max(0,Math.min(1,v));
function line(ctx,a,b,color,width=4,alpha=1){ctx.save();ctx.globalAlpha*=alpha;ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke();ctx.restore()}
function circle(ctx,x,y,r,fill,stroke=null,lw=3,alpha=1){ctx.save();ctx.globalAlpha*=alpha;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}ctx.restore()}
function rect(ctx,x,y,w,h,fill,stroke=null,r=16,alpha=1){ctx.save();ctx.globalAlpha*=alpha;ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=3;ctx.stroke()}ctx.restore()}
function label(ctx,text,x,y,T,size=24,align='center',alpha=1){ctx.save();ctx.globalAlpha*=alpha;ctx.font=`600 ${size}px Arial`;ctx.fillStyle=T.ink;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillText(text,x,y);ctx.restore()}
function active(m,i){const n=m.nodes[i];const reveal=Number.isFinite(n?.reveal)?n.reveal:(n?.active?1:0);return .18+.82*reveal}
function norm(m,i,W=1000,H=800){const p=m.nodes[i]?.position||{x:.5,y:.5};return [p.x*W,p.y*H]}
function drawGraph(ctx,T,m){const core=[500,400];circle(ctx,...core,74,T.accentSurface,T.accentText,4);label(ctx,'AI',...core,T,28);for(let i=0;i<m.nodes.length;i++){const p=norm(m,i),a=active(m,i);line(ctx,core,p,T.accent,4,a);circle(ctx,...p,42,T.surface,T.accent,4,a);label(ctx,String(i+1),...p,T,22,'center',a)}}
function drawContainment(ctx,T,m){const sizes=[[130,100],[220,170],[315,245],[410,320],[470,365]];sizes.slice(0,m.nodes.length).forEach(([w,h],i)=>rect(ctx,500-w/2,400-h/2,w,h,i%2?T.surface:T.accentSurface,T.accent,22,active(m,i)));label(ctx,'⊃',500,400,T,48)}
function drawAxes(ctx,T,m){line(ctx,[180,610],[820,610],T.rule,5);line(ctx,[180,610],[180,150],T.rule,5);line(ctx,[180,610],[720,230],T.accent,6,.9);for(let i=0;i<m.nodes.length;i++){const p=norm(m,i),a=active(m,i);circle(ctx,...p,30,T.accentSurface,T.accent,3,a);label(ctx,String(i+1),...p,T,18,'center',a)}}
function drawTransform(ctx,T,m){const a0=active(m,0),a1=active(m,1),a2=active(m,2);rect(ctx,110,285,300,210,T.surface,T.rule,22,a0);rect(ctx,590,285,300,210,T.accentSurface,T.accent,22,a1);line(ctx,[430,390],[570,390],T.accent,7,a1);label(ctx,'R(x)',260,390,T,30,'center',a0);label(ctx,'θ*',740,390,T,34,'center',a1);rect(ctx,250,555,500,70,T.accentSurface,T.accent,14,a2);label(ctx,'D + J(θ)',500,590,T,26,'center',a2)}
function drawRoadmap(ctx,T,m){for(let i=0;i<m.nodes.length;i++){const x=140+i*(720/Math.max(1,m.nodes.length-1)),y=420+(i%2?70:-70),a=active(m,i);if(i)line(ctx,[140+(i-1)*(720/Math.max(1,m.nodes.length-1)),420+((i-1)%2?70:-70)],[x,y],T.rule,5,a);circle(ctx,x,y,36,T.accentSurface,T.accent,4,a);label(ctx,String(i+1),x,y,T,20,'center',a)}}
function drawLoop(ctx,T,m){const pts=[[500,150],[800,400],[500,650],[200,400]];for(let i=0;i<pts.length;i++){const a=active(m,i);line(ctx,pts[i],pts[(i+1)%pts.length],T.rule,5,a);circle(ctx,...pts[i],46,T.surface,T.accent,4,a);label(ctx,String(i+1),...pts[i],T,20,'center',a)}}
function drawSwitchboard(ctx,T,m){for(let i=0;i<m.nodes.length;i++){const y=165+i*140,a=active(m,i);rect(ctx,120,y,250,80,T.surface,T.rule,14,a);line(ctx,[370,y+40],[690,400],T.accent,4,a);label(ctx,String(i+1),245,y+40,T,20,'center',a)}rect(ctx,690,310,200,180,T.accentSurface,T.accent,20);label(ctx,'learner',790,400,T,26)}
function drawGrid(ctx,T,m){for(let i=0;i<m.nodes.length;i++){const [x,y]=norm(m,i),a=active(m,i);rect(ctx,x-130,y-80,260,160,i%2?T.surface:T.accentSurface,T.rule,18,a);label(ctx,String(i+1),x,y,T,22,'center',a)}}
function drawDistribution(ctx,T,m){ctx.save();ctx.strokeStyle=T.rule;ctx.lineWidth=4;ctx.beginPath();for(let x=100;x<=900;x+=8){const y=540-190*Math.exp(-(((x-350)/170)**2));x===100?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.stroke();ctx.strokeStyle=T.accent;ctx.beginPath();for(let x=100;x<=900;x+=8){const center=350+260*clamp(m.progress);const y=540-190*Math.exp(-(((x-center)/170)**2));x===100?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.stroke();ctx.restore()}
function drawVector(ctx,T,m){line(ctx,[190,620],[810,180],T.rule,4);for(let i=0;i<m.nodes.length;i++){const [x,y]=norm(m,i),a=active(m,i);circle(ctx,x,y,34,T.accentSurface,T.accent,3,a);if(i)line(ctx,norm(m,i-1),[x,y],T.accent,3,a)}}
function drawAttention(ctx,T,m){const c=[500,400];for(let i=0;i<m.nodes.length;i++){const p=norm(m,i),a=active(m,i);line(ctx,c,p,T.accent,Math.max(2,8-i),a);circle(ctx,...p,34,T.surface,T.accent,3,a)}circle(ctx,...c,58,T.accentSurface,T.accent,4);label(ctx,'Q',...c,T,28)}
function drawBudget(ctx,T,m){const bars=[.36,.58,.78,.48,.66];for(let i=0;i<Math.min(m.nodes.length,bars.length);i++){const x=150+i*170,h=360*bars[i]*active(m,i);rect(ctx,x,610-h,90,h,T.accentSurface,T.accent,10,1);label(ctx,String(i+1),x+45,650,T,18)}}
function drawStack(ctx,T,m){for(let i=0;i<m.nodes.length;i++){const w=280+i*110,x=500-w/2,y=610-i*105,a=active(m,i);rect(ctx,x,y,w,78,i%2?T.surface:T.accentSurface,T.accent,14,a);label(ctx,String(i+1),500,y+39,T,20,'center',a)}}
function drawFanout(ctx,T,m){const root=[180,400];circle(ctx,...root,44,T.accentSurface,T.accent,4);for(let i=0;i<m.nodes.length;i++){const y=150+i*(500/Math.max(1,m.nodes.length-1)),p=[800,y],a=active(m,i);line(ctx,root,p,T.accent,4,a);circle(ctx,...p,32,T.surface,T.accent,3,a)}}
function drawSpectrum(ctx,T,m){line(ctx,[120,420],[880,420],T.rule,18);for(let i=0;i<m.nodes.length;i++){const x=160+i*(680/Math.max(1,m.nodes.length-1)),a=active(m,i);circle(ctx,x,420,28,T.accentSurface,T.accent,4,a);label(ctx,String(i+1),x,485,T,18,'center',a)}}
function drawPipeline(ctx,T,m){const lanes=Math.max(2,Math.min(4,m.nodes.length));for(let i=0;i<lanes;i++){const y=180+i*160,a=active(m,i);line(ctx,[140,y],[860,y],i%2?T.rule:T.accent,7,a);circle(ctx,140,y,22,T.surface,T.accent,3,1);circle(ctx,860,y,22,T.accentSurface,T.accent,3,a)}}
function drawDecision(ctx,T,m){const root=[500,150];circle(ctx,...root,42,T.accentSurface,T.accent,4);const leaves=[[220,400],[500,400],[780,400],[360,650],[640,650]];leaves.slice(0,m.nodes.length).forEach((p,i)=>{const a=active(m,i);line(ctx,root,p,T.accent,4,a);rect(ctx,p[0]-72,p[1]-38,144,76,T.surface,T.rule,14,a);label(ctx,String(i+1),...p,T,20,'center',a)})}
function drawOverlap(ctx,T,m){const a=.18+.62*clamp(m.progress*2),b=.18+.62*clamp(m.progress*2-.45);circle(ctx,430,400,170,T.accentSurface,T.accent,4,a);circle(ctx,570,400,170,T.surface,T.accentText,4,b);label(ctx,'A',370,400,T,28,'center',a);label(ctx,'B',630,400,T,28,'center',b);label(ctx,'∩',500,400,T,32,'center',Math.max(a,b))}
function drawLadder(ctx,T,m){for(let i=0;i<m.nodes.length;i++){const x=180+i*130,y=650-i*110,a=active(m,i);rect(ctx,x,y,120,70,i%2?T.surface:T.accentSurface,T.accent,12,a);if(i)line(ctx,[x-10,y+35],[x-60,y+145],T.rule,4,a);label(ctx,String(i+1),x+60,y+35,T,20,'center',a)}}
function drawRadar(ctx,T,m){const c=[500,400],R=270;for(const r of [90,180,270])circle(ctx,...c,r,null,T.rule,2);for(let i=0;i<m.nodes.length;i++){const a=-Math.PI/2+i*2*Math.PI/m.nodes.length,p=[c[0]+Math.cos(a)*R*.78,c[1]+Math.sin(a)*R*.78],q=active(m,i);line(ctx,c,p,T.rule,2,q);circle(ctx,...p,24,T.accentSurface,T.accent,3,q)}}
function drawGap(ctx,T,m){line(ctx,[140,610],[860,200],T.rule,7);line(ctx,[140,610],[860,380],T.accent,7,clamp(m.progress*1.2));line(ctx,[860,200],[860,380],T.accentText,5);label(ctx,'gap',830,290,T,22,'right')}
export function drawFundamentosMechanism(ctx,T,m){const style=m.style;ctx.save();switch(style){case'lattice':drawGraph(ctx,T,m);break;case'containment':drawContainment(ctx,T,m);break;case'axes':drawAxes(ctx,T,m);break;case'transform':drawTransform(ctx,T,m);break;case'roadmap':drawRoadmap(ctx,T,m);break;case'control-loop':case'cycle':drawLoop(ctx,T,m);break;case'switchboard':drawSwitchboard(ctx,T,m);break;case'comparison-grid':drawGrid(ctx,T,m);break;case'distribution':drawDistribution(ctx,T,m);break;case'vector-space':drawVector(ctx,T,m);break;case'attention-web':drawAttention(ctx,T,m);break;case'budget-surface':drawBudget(ctx,T,m);break;case'hub':drawGraph(ctx,T,m);break;case'capability-stack':drawStack(ctx,T,m);break;case'output-space':drawGrid(ctx,T,m);break;case'fanout-tree':drawFanout(ctx,T,m);break;case'spectrum':drawSpectrum(ctx,T,m);break;case'parallel-pipeline':case'parallel-lanes':drawPipeline(ctx,T,m);break;case'decision-tree':drawDecision(ctx,T,m);break;case'overlap-map':drawOverlap(ctx,T,m);break;case'ladder':drawLadder(ctx,T,m);break;case'boundary-radar':drawRadar(ctx,T,m);break;case'trajectory-gap':drawGap(ctx,T,m);break;default:throw new Error(`fundamentos visuals: unsupported style ${style}`)}ctx.restore()}
