#!/usr/bin/env node
/** Bounded Security02-05 real-browser evidence. Manual PIXEL/PEDAGOGY remains separate. */
import fs from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright';

const base=process.env.S5_PREVIEW_BASE||'http://127.0.0.1:8000';
const out=path.resolve('artifacts/security-requalification/security-02-05-browser-fast');
const shots=path.join(out,'screenshots'); await fs.mkdir(shots,{recursive:true});
const routes=[
 {chapter:'02',locale:'es',route:'/series/seguridad-ia/02-jailbreaks/'},{chapter:'02',locale:'en',route:'/en/series/seguridad-ia/02-jailbreaks/'},
 {chapter:'03',locale:'es',route:'/series/seguridad-ia/03-envenenamiento/'},{chapter:'03',locale:'en',route:'/en/series/seguridad-ia/03-envenenamiento/'},
 {chapter:'04',locale:'es',route:'/series/seguridad-ia/04-red-teaming/'},{chapter:'04',locale:'en',route:'/en/series/seguridad-ia/04-red-teaming/'},
 {chapter:'05',locale:'es',route:'/series/seguridad-ia/05-controles-produccion/'},{chapter:'05',locale:'en',route:'/en/series/seguridad-ia/05-controles-produccion/'}
];
const specs=[
 {name:'desktop-normal',width:1440,height:1000,mobile:false,reducedMotion:'no-preference'},
 {name:'desktop-reduced',width:1440,height:1000,mobile:false,reducedMotion:'reduce'},
 {name:'mobile-normal',width:390,height:844,mobile:true,reducedMotion:'no-preference'},
 {name:'mobile-reduced',width:390,height:844,mobile:true,reducedMotion:'reduce'}
];
const failures=[],records=[]; const check=(ok,message,detail=null)=>{if(!ok) failures.push({message,detail});};
const safe=s=>s.replace(/[^a-zA-Z0-9_-]+/g,'-');
async function shot(loc,name){await loc.scrollIntoViewIfNeeded();const f=path.join(shots,`${safe(name)}.png`);await loc.screenshot({path:f,animations:'disabled'});return path.relative(process.cwd(),f);}
async function activate(loc,mobile,keyboard=false){await loc.scrollIntoViewIfNeeded();if(keyboard){await loc.focus();await loc.press('Enter');}else if(mobile) await loc.tap({timeout:3000});else await loc.click({timeout:3000});await new Promise(r=>setTimeout(r,35));}
async function focusVisible(loc){await loc.focus();return loc.evaluate(n=>{const s=getComputedStyle(n);return {active:document.activeElement===n,visible:n.matches(':focus-visible')||s.outlineStyle!=='none'||s.boxShadow!=='none',outline:s.outlineStyle,shadow:s.boxShadow};});}
async function inspect02(page,ctx,r){const root=page.locator('.jbladder').first();check(await root.count()===1,`${ctx}: jbladder missing`);if(!await root.count())return;r.screenshots.push(await shot(root,`${ctx}-02-start`));const a=root.locator('[data-toggle="actionable"]'),w=root.locator('[data-toggle="write"]'),u=root.locator('[data-toggle="auth"]'),badge=root.locator('[data-badge]'),route=root.locator('[data-route]');const f=await focusVisible(a);check(f.active&&f.visible,`${ctx}: 02 focus not visible`,f);const p0=await route.getAttribute('points');await activate(a,r.mobile,!r.mobile);check((await badge.textContent()).trim()==='READ_ONLY_BOUNDARY',`${ctx}: 02 read-only state missing`);r.screenshots.push(await shot(root,`${ctx}-02-actionable`));await activate(w,r.mobile);check((await badge.textContent()).trim()==='AUTH_BLOCKED',`${ctx}: 02 auth-blocked state missing`);r.screenshots.push(await shot(root,`${ctx}-02-write`));await activate(u,r.mobile);check((await badge.textContent()).trim()==='EXTERNAL_EFFECT',`${ctx}: 02 external-effect state missing`);const p1=await route.getAttribute('points');check(p1!==p0&&p1.trim().split(/\s+/).length>=5,`${ctx}: 02 route geometry did not extend`,{p0,p1});r.states.push({mechanism:'outcome-reachability',p0,p1,sequence:['TEXT_ONLY','READ_ONLY_BOUNDARY','AUTH_BLOCKED','EXTERNAL_EFFECT']});r.screenshots.push(await shot(root,`${ctx}-02-effect`));}
async function inspect03(page,ctx,r){const runtime=page.locator('.memlayers').first();check(await runtime.count()===1,`${ctx}: memlayers missing`);if(await runtime.count()){r.screenshots.push(await shot(runtime,`${ctx}-03-runtime-start`));const first=runtime.locator('[data-scenario="runtime"]'),f=await focusVisible(first);check(f.active&&f.visible,`${ctx}: 03 runtime focus not visible`,f);await activate(runtime.locator('[data-intervention="clear-runtime"]'),r.mobile,!r.mobile);check(await runtime.getAttribute('data-result')==='blocked',`${ctx}: 03 runtime path not cut`);r.screenshots.push(await shot(runtime,`${ctx}-03-runtime-cleared`));await activate(runtime.locator('[data-scenario="weights"]'),r.mobile);check(await runtime.getAttribute('data-result')==='risk',`${ctx}: 03 weights path not active`);r.screenshots.push(await shot(runtime,`${ctx}-03-weights-risk`));await activate(runtime.locator('[data-intervention="swap-model"]'),r.mobile);check(await runtime.getAttribute('data-result')==='blocked',`${ctx}: 03 weights path not cut`);r.screenshots.push(await shot(runtime,`${ctx}-03-runtime-cut`));r.states.push({mechanism:'runtime-vs-weights',sequence:['runtime-risk','runtime-cleared','weights-risk','weights-swapped']});}
 const prop=page.locator('.memprop').first();check(await prop.count()===1,`${ctx}: memprop missing`);if(await prop.count()){r.screenshots.push(await shot(prop,`${ctx}-03-prop-start`));const p=prop.locator('[data-action="propagate"]'),f=await focusVisible(p);check(f.active&&f.visible,`${ctx}: 03 propagation focus not visible`,f);await activate(p,r.mobile,!r.mobile);check(await prop.getAttribute('data-state')==='propagated',`${ctx}: 03 not propagated`);r.screenshots.push(await shot(prop,`${ctx}-03-prop-propagated`));await activate(prop.locator('[data-action="delete-origin"]'),r.mobile);check(await prop.getAttribute('data-state')==='origin-deleted',`${ctx}: 03 residual derivative state missing`);const result=(await prop.locator('[data-result]').textContent()||'').toUpperCase();check(result.includes('DERIV'),`${ctx}: 03 derivative reachability not visible`,result);r.screenshots.push(await shot(prop,`${ctx}-03-prop-origin-deleted`));await activate(prop.locator('[data-action="invalidate"]'),r.mobile);check(await prop.getAttribute('data-state')==='invalidated',`${ctx}: 03 lineage not invalidated`);r.screenshots.push(await shot(prop,`${ctx}-03-prop-invalidated`));r.states.push({mechanism:'derived-lineage',sequence:['clean','propagated','origin-deleted-derivatives-live','invalidated']});}}
async function inspect04(page,ctx,r){const root=page.locator('.regloop').first();check(await root.count()===1,`${ctx}: regloop missing`);if(!await root.count())return;r.screenshots.push(await shot(root,`${ctx}-04-start`));const blocked=root.locator('[data-toggle="blocked"]'),f=await focusVisible(blocked);check(f.active&&f.visible,`${ctx}: 04 focus not visible`,f);check(await root.locator('[data-outcome]').getAttribute('data-release')==='HOLD',`${ctx}: 04 initial HOLD missing`);await activate(blocked,r.mobile,!r.mobile);check(await root.locator('[data-outcome]').getAttribute('data-release')==='DEPLOY',`${ctx}: 04 DEPLOY state missing`);r.screenshots.push(await shot(root,`${ctx}-04-deploy`));await activate(root.locator('[data-toggle="legit"]'),r.mobile);check(await root.locator('[data-outcome]').getAttribute('data-release')==='HOLD',`${ctx}: 04 legitimate-regression HOLD missing`);if(r.mobile)check((await root.locator('[data-mobile="gate"]').textContent()).includes('HOLD'),`${ctx}: 04 mobile HOLD missing`);r.screenshots.push(await shot(root,`${ctx}-04-hold`));r.states.push({mechanism:'release-regression-gate',sequence:['attack-persists-hold','attack-blocked-deploy','legitimate-regression-hold']});}
async function inspect05(page,ctx,r){const root=page.locator('.releasegate').first();check(await root.count()===1,`${ctx}: releasegate missing`);if(!await root.count())return;r.screenshots.push(await shot(root,`${ctx}-05-start`));const authority=root.locator('[data-mode="authority"]'),f=await focusVisible(authority);check(f.active&&f.visible,`${ctx}: 05 focus not visible`,f);check(await root.locator('[data-output="deploy"]').isVisible()&&!await root.locator('[data-output="hold"]').isVisible(),`${ctx}: 05 initial topology is not DEPLOY`);await activate(authority,r.mobile,!r.mobile);check(!await root.locator('[data-output="deploy"]').isVisible()&&await root.locator('[data-output="hold"]').isVisible(),`${ctx}: 05 authority failure did not switch topology to HOLD`);r.screenshots.push(await shot(root,`${ctx}-05-authority-hold`));await activate(root.locator('[data-mode="state"]'),r.mobile);check((await root.locator('[data-decision]').textContent()).trim()==='HOLD',`${ctx}: 05 state did not HOLD`);r.screenshots.push(await shot(root,`${ctx}-05-state-hold`));await activate(root.locator('[data-mode="recovery"]'),r.mobile);check((await root.locator('[data-decision]').textContent()).trim()==='HOLD',`${ctx}: 05 recovery did not HOLD`);r.screenshots.push(await shot(root,`${ctx}-05-recovery-hold`));await activate(root.locator('[data-mode="pass"]'),r.mobile);check((await root.locator('[data-decision]').textContent()).trim()==='DEPLOY',`${ctx}: 05 recovery to DEPLOY failed`);r.screenshots.push(await shot(root,`${ctx}-05-restored`));r.states.push({mechanism:'evidence-bound-release-gate',sequence:['all-evidence-deploy','authority-stale-hold','state-contract-drift-hold','recovery-unverified-hold','evidence-restored-deploy']});}
async function runOne(browser,item,spec){const context=await browser.newContext({viewport:{width:spec.width,height:spec.height},hasTouch:spec.mobile,isMobile:spec.mobile,reducedMotion:spec.reducedMotion,colorScheme:'light'});const page=await context.newPage();const ctx=`${item.locale}-security${item.chapter}-${spec.name}`,r={...item,context:spec.name,mobile:spec.mobile,motion:spec.reducedMotion,screenshots:[],states:[],runtime:[]};let phase='nav';page.on('pageerror',e=>r.runtime.push({type:'pageerror',phase,detail:String(e)}));page.on('console',m=>{if(m.type()==='error')r.runtime.push({type:'console',phase,detail:m.text()});});page.on('requestfailed',q=>r.runtime.push({type:'requestfailed',phase,url:q.url(),detail:q.failure()?.errorText||'unknown'}));page.on('response',x=>{if(x.status()>=400)r.runtime.push({type:'http',phase,status:x.status(),url:x.url()});});try{const response=await page.goto(new URL(item.route,base).href,{waitUntil:'domcontentloaded',timeout:10000});check(Boolean(response&&response.ok()),`${ctx}: navigation failed`,response?.status());await page.locator('article').waitFor({state:'visible',timeout:5000});await page.waitForTimeout(100);phase='interaction';const geo=await page.evaluate(()=>({viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,bodyWidth:document.body.scrollWidth}));r.geometry=geo;check(geo.scrollWidth<=geo.viewport+2&&geo.bodyWidth<=geo.viewport+2,`${ctx}: page overflow`,geo);if(item.chapter==='02')await inspect02(page,ctx,r);if(item.chapter==='03')await inspect03(page,ctx,r);if(item.chapter==='04')await inspect04(page,ctx,r);if(item.chapter==='05')await inspect05(page,ctx,r);const post=await page.evaluate(()=>({viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,bodyWidth:document.body.scrollWidth}));r.postGeometry=post;check(post.scrollWidth<=post.viewport+2&&post.bodyWidth<=post.viewport+2,`${ctx}: interaction overflow`,post);}catch(e){failures.push({message:`${ctx}: exception`,detail:String(e?.stack||e)});}phase='teardown';await page.waitForTimeout(50);const fatal=r.runtime.filter(e=>!(e.type==='requestfailed'&&e.phase==='teardown'&&String(e.detail).includes('ERR_ABORTED')));check(fatal.length===0,`${ctx}: runtime/resource failures`,fatal);records.push(r);await context.close();}
let browser;try{browser=await chromium.launch({channel:'chrome',headless:true});}catch{browser=await chromium.launch({headless:true});}
for(const item of routes){await Promise.all(specs.map(spec=>runOne(browser,item,spec)));}
await browser.close();
await fs.writeFile(path.join(out,'report.json'),JSON.stringify({generated_at:new Date().toISOString(),contract:'technical browser evidence + complete meaningful state capture; manual PIXEL/PEDAGOGY required',contexts:records.length,failures,records},null,2));
console.log(`SECURITY02_05_BROWSER_FAST contexts=${records.length} failures=${failures.length}`);if(failures.length){for(const f of failures)console.error('FAIL',f.message,f.detail||'');process.exit(1);}console.log('PASS bounded Security02-05 browser gate with meaningful start/intermediate/final state capture; manual PIXEL/PEDAGOGY still required.');
