#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright';

const base=process.env.S5_PREVIEW_BASE||'http://127.0.0.1:8000';
const outDir=path.resolve('artifacts/visual-review');await fs.mkdir(outDir,{recursive:true});
const failures=[];const check=(c,m)=>{if(!c)failures.push(m);};
const cases=[
 {locale:'es',route:'/series/context-engineering-memory-mcp/05-mcp-hosts-clients-servers-tools-resources-prompts-lifecycle-trust-boundaries/',required:['MCP ≠ confianza implícita','HOST · ORQUESTACIÓN + POLÍTICA','USUARIO','MODELO','POLÍTICA DEL HOST','CLIENT A','1:1 con server A','CLIENT B','1:1 con server B','SERVER A · LOCAL / STDIO','RESOURCES','SERVER B · REMOTO / HTTP','AUTH MCP','OTRA FRONTERA · SISTEMA DOWNSTREAM','AUTH DOWNSTREAM','token propio · no passthrough','EFECTO EXTERNO','2026-07-28: versión + capabilities por request','≤ 2025-11-25: initialize · legacy'],forbidden:['MCP ≠ implicit trust','HOST POLICY','REMOTE / HTTP','DOWNSTREAM AUTH','EXTERNAL EFFECT']},
 {locale:'en',route:'/en/series/context-engineering-memory-mcp/05-mcp-hosts-clients-servers-tools-resources-prompts-lifecycle-trust-boundaries/',required:['MCP ≠ implicit trust','HOST · ORCHESTRATION + POLICY','USER','MODEL','HOST POLICY','CLIENT A','1:1 with server A','CLIENT B','1:1 with server B','SERVER A · LOCAL / STDIO','RESOURCES','SERVER B · REMOTE / HTTP','MCP AUTH','ANOTHER BOUNDARY · DOWNSTREAM SYSTEM','DOWNSTREAM AUTH','separate token · no passthrough','EXTERNAL EFFECT','2026-07-28: version + capabilities per request','≤ 2025-11-25: initialize · legacy'],forbidden:['confianza implícita','POLÍTICA DEL HOST','REMOTO / HTTP','OTRA FRONTERA','EFECTO EXTERNO','credencial distinta','aislados entre sí']},
];
const viewports=[{name:'desktop',width:1440,height:1000,hasTouch:false},{name:'mobile',width:390,height:844,hasTouch:true}];
const browser=await chromium.launch({headless:true});
try{
 for(const testCase of cases)for(const viewport of viewports){
  const context=await browser.newContext({viewport:{width:viewport.width,height:viewport.height},hasTouch:viewport.hasTouch,isMobile:viewport.hasTouch,reducedMotion:'reduce'});const page=await context.newPage();const runtimeErrors=[];const consoleErrors=[];
  page.on('pageerror',e=>runtimeErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});
  const response=await page.goto(`${base}${testCase.route}`,{waitUntil:'networkidle'});check(response?.ok(),`${testCase.route}: ${viewport.name} HTTP ${response?.status()??'no response'}`);
  const lang=await page.locator('html').getAttribute('lang');check((lang||'').toLowerCase().startsWith(testCase.locale),`${testCase.route}: ${viewport.name} wrong html lang ${lang}`);check(await page.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),`${testCase.route}: reduced-motion inactive`);
  const visual=page.locator('.s5v-context-mcp-trust');check((await visual.count())===1,`${testCase.route}: ${viewport.name} expected one MCP visual`);
  if(await visual.count()){
   const label=(await visual.getAttribute('aria-label'))?.trim()||'';check(label.length>=70,`${testCase.route}: ${viewport.name} weak aria-label`);const text=(await visual.innerText()).toLowerCase();for(const t of testCase.required)check(text.includes(t.toLowerCase()),`${testCase.route}: ${viewport.name} missing ${JSON.stringify(t)}`);for(const t of testCase.forbidden)check(!text.includes(t.toLowerCase()),`${testCase.route}: ${viewport.name} untranslated ${JSON.stringify(t)}`);
   check((await visual.locator('.s5v-arch-map__pipe,.s5v__steps--tabs,[data-s5v-stepper],[data-s5v-tabs]').count())===0,`${testCase.route}: cosmetic/linear visual regression`);
   const g=await visual.evaluate(root=>{const box=s=>{const n=root.querySelector(s);if(!n)return null;const r=n.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height,cx:r.left+r.width/2,cy:r.top+r.height/2};};return{host:box('[data-boundary="host"]'),aB:box('[data-boundary="server-a"]'),bB:box('[data-boundary="server-b"]'),down:box('[data-boundary="downstream"]'),life:box('[data-boundary="lifecycle"]'),user:box('[data-node="user"]'),model:box('[data-node="model"]'),policy:box('[data-node="host-policy"]'),a:box('[data-node="client-a"]'),b:box('[data-node="client-b"]'),sa:box('[data-node="server-a"]'),sb:box('[data-node="server-b"]'),mcpAuth:box('[data-node="mcp-auth"]'),downAuth:box('[data-node="downstream-auth"]'),effect:box('[data-node="external-effect"]'),modelPolicy:box('[data-edge="model-policy"]'),policyB:box('[data-edge="policy-client-b"]'),bLink:box('[data-edge="client-b-server-b"]'),sbAuth:box('[data-edge="server-b-auth"]'),resourceBack:box('[data-edge="resource-back-a"]'),serverDown:box('[data-edge="server-downstream-auth"]'),authEffect:box('[data-edge="auth-effect"]'),modern:box('[data-edge="modern-request"]'),legacy:box('[data-edge="legacy-initialize"]')};});
   for(const [n,b] of Object.entries(g))check(Boolean(b&&b.width>=0&&b.height>=0),`${testCase.route}: ${viewport.name} missing geometry ${n}`);
   if(g.host&&g.aB&&g.bB&&g.down){check(g.host.right<g.aB.left+5,`${testCase.route}: host/server A boundaries overlap`);check(g.host.right<g.bB.left+5,`${testCase.route}: host/server B boundaries overlap`);check(g.bB.right<g.down.left+5,`${testCase.route}: MCP/downstream boundaries overlap`);check(g.aB.bottom<g.bB.top+5,`${testCase.route}: server isolation collapsed`);}
   if(g.user&&g.model&&g.policy&&g.a&&g.b){check(Math.abs(g.user.cy-g.model.cy)<12,`${testCase.route}: user/model peer layout lost`);check(g.policy.cy>g.model.cy+90,`${testCase.route}: model→host policy hierarchy collapsed`);check(Math.abs(g.a.cy-g.b.cy)<12,`${testCase.route}: client peer lanes lost`);check(g.b.cy>g.policy.cy+110,`${testCase.route}: policy→client layer collapsed`);}
   if(g.modelPolicy&&g.policyB&&g.bLink&&g.sbAuth){check(g.modelPolicy.height>30,`${testCase.route}: model→policy tool proposal collapsed`);check(g.policyB.height>45,`${testCase.route}: policy/approval→client B path collapsed`);check(g.bLink.width>100,`${testCase.route}: client B→server B path collapsed`);check(g.sbAuth.height>20,`${testCase.route}: server B→MCP auth path collapsed`);}
   if(g.resourceBack)check(g.resourceBack.width>250&&g.resourceBack.height>200,`${testCase.route}: inbound resource path collapsed`);
   if(g.mcpAuth&&g.downAuth&&g.effect&&g.serverDown&&g.authEffect){check(g.downAuth.cx>g.mcpAuth.cx+250,`${testCase.route}: downstream auth boundary lost`);check(g.serverDown.width>100,`${testCase.route}: MCP→downstream crossing collapsed`);check(g.effect.cy>g.downAuth.cy+90&&g.authEffect.height>30,`${testCase.route}: authorization→effect consequence collapsed`);}
   if(g.life&&g.host&&g.modern&&g.legacy){check(g.life.top>g.host.bottom+20,`${testCase.route}: lifecycle lane collapsed into trust topology`);check(g.modern.width>80&&g.legacy.width>100,`${testCase.route}: modern/legacy lifecycle distinction collapsed`);}
   const scroller=visual.locator('.mt-scroll');check((await scroller.count())===1,`${testCase.route}: topology-preserving scroll region missing`);if(await scroller.count()){check((await scroller.getAttribute('tabindex'))==='0',`${testCase.route}: scroll region not focusable`);const state=await scroller.evaluate(node=>{const maxScroll=node.scrollWidth-node.clientWidth;node.scrollLeft=maxScroll;void node.offsetWidth;const stage=node.querySelector('.mt-stage')?.getBoundingClientRect();const r=node.getBoundingClientRect();return{maxScroll,actualScroll:node.scrollLeft,stageWidth:stage?.width??0,stageRight:stage?.right??0,scrollerRight:r.right};});if(viewport.name==='mobile'){check(state.maxScroll>450&&state.actualScroll>450,`${testCase.route}: mobile topology did not survive scroll ${JSON.stringify(state)}`);await scroller.screenshot({path:path.join(outDir,`context-engineering-ch5-${testCase.locale}-mobile-visual-end.png`),animations:'disabled'});}else{check(state.maxScroll<=1&&state.actualScroll<=1,`${testCase.route}: desktop clips horizontally ${JSON.stringify(state)}`);check(state.stageWidth>=900&&state.stageRight<=state.scrollerRight+1,`${testCase.route}: desktop stage escapes viewport ${JSON.stringify(state)}`);}await scroller.evaluate(node=>{node.scrollLeft=0;});}
   await visual.screenshot({path:path.join(outDir,`context-engineering-ch5-${testCase.locale}-${viewport.name}-visual.png`),animations:'disabled'});
  }
  const article=(await page.locator('main').innerText()).toLowerCase();for(const t of ['mcp','host','client','server','tool','resource','prompt','authorization','2026-07-28'])check(article.includes(t),`${testCase.route}: article missing ${t}`);const overflow=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth}));check(overflow.scrollWidth<=overflow.clientWidth+1,`${testCase.route}: ${viewport.name} page overflow ${JSON.stringify(overflow)}`);for(const e of runtimeErrors)failures.push(`${testCase.route}: ${viewport.name} runtime error: ${e}`);for(const e of consoleErrors.filter(x=>!/favicon|Failed to load resource.*404/i.test(x)))failures.push(`${testCase.route}: ${viewport.name} console error: ${e}`);await page.screenshot({path:path.join(outDir,`context-engineering-ch5-${testCase.locale}-${viewport.name}-page.png`),fullPage:true,animations:'disabled'});await context.close();
 }
}finally{await browser.close();}
if(failures.length){console.error(`Context engineering chapter 3.5 browser/accessibility QA failed (${failures.length}):`);for(const f of failures)console.error(`- ${f}`);process.exit(1);}console.log('Context engineering chapter 3.5 browser/accessibility QA PASS: host policy, client/server isolation, inbound context, outbound side-effect authorization, modern/legacy lifecycle, desktop/mobile geometry, reduced-motion and overflow are valid.');
