#!/usr/bin/env python3
"""Fail-closed Security 00/01 article↔watch and locale-renderer contract.

English and Spanish watch pages are generated by different canonical hooks.
This focused fixture deliberately exercises the real renderer for each locale,
plus one Datacenters reference surface, so a test cannot create a false locale
failure by calling the Spanish renderer for English output.

The active Security00 presentation also carries reader navigation that must stay
ES/EN equivalent. This gate therefore verifies the real Markdown sources for the
related-series and series-hub links and runs an in-process negative mutation so
removing one locale link cannot silently pass.

This gate does not certify MEDIA_PASS, pixel quality, pedagogy, or the global
catalogue.
"""
from __future__ import annotations

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from hooks.video_embed import _watch_url
from hooks.video_sitemap import _hub_schema as es_hub_schema
from hooks.video_sitemap import _render_hub as es_render_hub
from hooks.video_sitemap import _render_watch_page as es_render_watch
from hooks.video_sitemap import _video_schema as es_video_schema
from hooks.video_sitemap_en import _hub_schema as en_hub_schema
from hooks.video_sitemap_en import _render_hub as en_render_hub
from hooks.video_sitemap_en import _render_watch_page as en_render_watch
from hooks.video_sitemap_en import _video_schema as en_video_schema


TARGETS = (
    ("00_presentacion_serie.md", "00_presentacion_serie", "AI Security"),
    ("01-prompt-injection.md", "01-prompt-injection", "Prompt Injection"),
)

FORBIDDEN_EN_WATCH_UI = (
    "Todos los vídeos",
    "Resumen del vídeo",
    "Las ideas que debes retener",
    "Contexto y evidencia",
    "Continúa con el artículo completo",
    "Leer el artículo",
    "Siguiente paso",
    "Vídeos relacionados",
    "Tu navegador no soporta el elemento de vídeo.",
)

REQUIRED_EN_WATCH_UI = (
    "All videos",
    "Video summary",
    "The ideas to retain",
    "Context and evidence",
    "Continue with the full article",
    "Read the article →",
    "Next step",
    "Related videos",
    "Your browser does not support the video element.",
)

REQUIRED_ES_WATCH_UI = (
    "Todos los vídeos",
    "Resumen del vídeo",
    "Las ideas que debes retener",
    "Contexto y evidencia",
    "Continúa con el artículo completo",
    "Leer el artículo →",
    "Siguiente paso",
    "Vídeos relacionados",
    "Tu navegador no soporta el elemento de vídeo.",
)

SECURITY00_SOURCE = {
    "es": ROOT / "docs/series/seguridad-ia/00_presentacion_serie.md",
    "en": ROOT / "locales/en/series/seguridad-ia/00_presentacion_serie.md",
}

EXPECTED_SECURITY00_SERIES_LINKS = {
    "/series/modelos-razonadores/00_presentacion_serie/",
    "/series/agentes-ia/00_presentacion_serie/",
    "/series/",
}

MARKDOWN_LINK_RE = re.compile(r"\[[^\]]+\]\((/[^)\s]+)\)")


def _canonical_series_links(text: str, locale: str) -> tuple[set[str], list[str]]:
    links: set[str] = set()
    failures: list[str] = []
    for raw in MARKDOWN_LINK_RE.findall(text):
        path = raw.split("#", 1)[0].split("?", 1)[0]
        if locale == "en":
            if path.startswith("/series/"):
                failures.append(f"en: non-localized Spanish series link leaked: {path}")
                continue
            if not path.startswith("/en/series/"):
                continue
            path = path.removeprefix("/en")
        else:
            if path.startswith("/en/series/"):
                failures.append(f"es: English series link leaked: {path}")
                continue
            if not path.startswith("/series/"):
                continue
        links.add(path)
    return links, failures


def security00_navigation_failures(es_text: str, en_text: str) -> list[str]:
    failures: list[str] = []
    es_links, es_failures = _canonical_series_links(es_text, "es")
    en_links, en_failures = _canonical_series_links(en_text, "en")
    failures.extend(es_failures)
    failures.extend(en_failures)

    if "**Series relacionadas:**" not in es_text:
        failures.append("es/security00: related-series navigation label missing")
    if "[Ver todas las series](/series/)" not in es_text:
        failures.append("es/security00: all-series hub link missing")
    if "**Related series:**" not in en_text:
        failures.append("en/security00: related-series navigation label missing")
    if "[View all series](/en/series/)" not in en_text:
        failures.append("en/security00: all-series hub link missing")

    if es_links != EXPECTED_SECURITY00_SERIES_LINKS:
        failures.append(
            "es/security00: canonical series navigation mismatch: "
            f"expected={sorted(EXPECTED_SECURITY00_SERIES_LINKS)!r} got={sorted(es_links)!r}"
        )
    if en_links != EXPECTED_SECURITY00_SERIES_LINKS:
        failures.append(
            "en/security00: canonical series navigation mismatch: "
            f"expected={sorted(EXPECTED_SECURITY00_SERIES_LINKS)!r} got={sorted(en_links)!r}"
        )
    if es_links != en_links:
        failures.append(
            f"security00: ES/EN canonical series-link parity mismatch: es={sorted(es_links)!r} en={sorted(en_links)!r}"
        )
    return failures


def assert_security00_navigation_contract(failures: list[str]) -> None:
    missing = [str(path.relative_to(ROOT)) for path in SECURITY00_SOURCE.values() if not path.is_file()]
    if missing:
        failures.append(f"security00: navigation source missing: {missing!r}")
        return

    es_text = SECURITY00_SOURCE["es"].read_text(encoding="utf-8")
    en_text = SECURITY00_SOURCE["en"].read_text(encoding="utf-8")
    failures.extend(security00_navigation_failures(es_text, en_text))

    # Deterministic negative proof: the checker itself must reject a locale
    # mirror that drops one related-series route while retaining the labels.
    mutated_es = es_text.replace(
        " · [Agentes de IA](/series/agentes-ia/00_presentacion_serie/)",
        "",
        1,
    )
    mutation_failures = security00_navigation_failures(mutated_es, en_text)
    if not any("canonical series navigation mismatch" in item or "parity mismatch" in item for item in mutation_failures):
        failures.append("security00: negative navigation-parity mutation was not detected")


def entry(
    *,
    locale: str,
    source_name: str,
    stem: str,
    title: str,
    series: str = "seguridad-ia",
) -> dict:
    site_url = "https://5sigmas.com" if locale == "es" else "https://5sigmas.com/en"
    source_rel = f"series/{series}/{source_name}"
    source_url = f"{site_url}/series/{series}/{Path(source_name).stem}/"
    watch_url = f"{site_url}/videos/series/{series}/{stem}/"
    is_security = series == "seguridad-ia"
    if locale == "en":
        topic = "security" if is_security else "infrastructure"
        topic_label = "AI security" if is_security else "Infrastructure"
    else:
        topic = "seguridad" if is_security else "infraestructura"
        topic_label = "Seguridad en IA" if is_security else "Infraestructura"
    return {
        "id": f"{series}-{locale}-{stem}",
        "watch_url": watch_url,
        "video_url": f"{site_url}/series/{series}/{stem}.mp4",
        "video_playback_url": (
            f"/series/{series}/{stem}.mp4"
            if locale == "es"
            else f"/en/series/{series}/{stem}.mp4"
        ),
        "thumb_url": f"{site_url}/series/{series}/{stem}.jpg",
        "thumb_playback_url": (
            f"/series/{series}/{stem}.jpg"
            if locale == "es"
            else f"/en/series/{series}/{stem}.jpg"
        ),
        "captions_url": "",
        "captions_playback_url": "",
        "title": title,
        "description": "Focused watch-page regression fixture.",
        "publication_date": "2026-08-06T00:00:00+00:00",
        "source_url": source_url,
        "source_src_uri": source_rel,
        "duration_iso": "PT48S" if locale == "en" else "PT1M0S",
        "duration_seconds": 48 if locale == "en" else 60,
        "duration_label": "0:48" if locale == "en" else "1:00",
        "topic": topic,
        "topic_label": topic_label,
        "collection": topic_label,
        "snippets": [{"title": "Mechanism" if locale == "en" else "Mecanismo", "excerpt": ""}],
        "chapters": [],
        "transcript": "",
        "keywords": ["AI security" if locale == "en" else "seguridad IA"],
    }


def render_watch(current: dict, locale: str) -> str:
    if locale == "en":
        return en_render_watch(current, [], "https://5sigmas.com/en")
    return es_render_watch(current, [])


def video_schema(current: dict, locale: str) -> dict:
    if locale == "en":
        return en_video_schema(
            current,
            "https://5sigmas.com/en",
            "https://5sigmas.com",
        )
    return es_video_schema(current, "https://5sigmas.com")


def assert_watch_locale(failures: list[str], current: dict, locale: str) -> None:
    stem = Path(current["video_playback_url"]).stem
    html = render_watch(current, locale)
    expected_source_href = f'href="{current["source_url"]}"'
    if expected_source_href not in html or 'class="s5-video-watch__source-link"' not in html:
        failures.append(f"{locale}/{stem}: watch→article source link missing")
    if 'data-s5-watch-player' not in html:
        failures.append(f"{locale}/{stem}: watch player missing")

    if locale == "en":
        leaked = [text for text in FORBIDDEN_EN_WATCH_UI if text in html]
        if leaked:
            failures.append(
                f"en/{stem}: canonical English watch renderer leaks Spanish UI: {', '.join(leaked)}"
            )
        missing = [text for text in REQUIRED_EN_WATCH_UI if text not in html]
        if missing:
            failures.append(
                f"en/{stem}: canonical English watch renderer misses English UI: {', '.join(missing)}"
            )
        if 'href="https://5sigmas.com/en/videos/"' not in html:
            failures.append(f"en/{stem}: canonical English videos breadcrumb missing")
        if 'srclang="es"' in html or 'label="Español"' in html:
            failures.append(f"en/{stem}: Spanish caption metadata leaked")
    else:
        missing = [text for text in REQUIRED_ES_WATCH_UI if text not in html]
        if missing:
            failures.append(
                f"es/{stem}: Spanish watch renderer changed required UI: {', '.join(missing)}"
            )
        if 'href="/videos/"' not in html:
            failures.append(f"es/{stem}: canonical Spanish videos breadcrumb missing")

    schema = video_schema(current, locale)
    if schema.get("inLanguage") != locale:
        failures.append(
            f"{locale}/{stem}: VideoObject inLanguage={schema.get('inLanguage')!r}"
        )


def main() -> None:
    failures: list[str] = []
    security_entries: dict[str, list[dict]] = {"es": [], "en": []}

    assert_security00_navigation_contract(failures)

    for locale in ("es", "en"):
        site_url = "https://5sigmas.com" if locale == "es" else "https://5sigmas.com/en"
        for source_name, stem, title in TARGETS:
            src_path = f"series/seguridad-ia/{source_name}"
            expected_watch = f"{site_url}/videos/series/seguridad-ia/{stem}/"
            actual_watch = _watch_url(site_url, src_path, f"{stem}.mp4")
            if actual_watch != expected_watch:
                failures.append(
                    f"{locale}/{stem}: article→watch URL mismatch: {actual_watch!r} != {expected_watch!r}"
                )

            current = entry(locale=locale, source_name=source_name, stem=stem, title=title)
            security_entries[locale].append(current)
            assert_watch_locale(failures, current, locale)

    # Shared CSS/runtime regression reference without modifying Datacenters content.
    for locale, title in (("es", "Datacenters en el espacio"), ("en", "Datacenters in Space")):
        current = entry(
            locale=locale,
            source_name="00_presentacion_serie.md",
            stem="00_presentacion_serie",
            title=title,
            series="datacenters-espacio",
        )
        assert_watch_locale(failures, current, locale)

    es_hub = es_render_hub(security_entries["es"])
    en_hub = en_render_hub(security_entries["en"], "https://5sigmas.com/en")
    for text in ("Vídeos de inteligencia artificial", "Biblioteca de vídeo", "Explorar las series"):
        if text not in es_hub:
            failures.append(f"es: canonical Spanish hub changed {text!r}")
    for text in ("Artificial intelligence videos", "Video library", "Explore the series"):
        if text not in en_hub:
            failures.append(f"en: canonical English hub misses {text!r}")
    for text in ("Vídeos de inteligencia artificial", "Biblioteca de vídeo", "Explorar las series"):
        if text in en_hub:
            failures.append(f"en: canonical English hub leaks Spanish UI {text!r}")

    if es_hub_schema(security_entries["es"], "https://5sigmas.com").get("inLanguage") != "es":
        failures.append("es: CollectionPage inLanguage mismatch")
    if en_hub_schema(security_entries["en"], "https://5sigmas.com/en").get("inLanguage") != "en":
        failures.append("en: CollectionPage inLanguage mismatch")

    if failures:
        print("SECURITY_ARTICLE_WATCH_CONTRACT=FAIL")
        for failure in failures:
            print(f"- {failure}")
        raise SystemExit(1)

    print("SECURITY_ARTICLE_WATCH_CONTRACT=PASS")


if __name__ == "__main__":
    main()
