#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright';

const base=process.env.S5_PREVIEW_BASE||'http://127.0.0.1:8000';
const outDir=path.resolve('artifacts/visual-review');await fs.mkdir(outDir,{recursive:true});
const failures=[];const check=(c,m)=>{if(!c)failures.push(m);};
const cases=[
 {locale:'es',route:'/series/context-engineering-memory-mcp/06-skills-plugins-subagents-hooks-context-isolation-evaluation/',required:['Paquete ≠ contexto ≠ autoridad','PLUGIN · DISTRIBUCIÓN','SKILL','DEFINICIÓN SUBAGENTE','CONFIGURACIÓN HOOK','CONTEXTO PADRE Cₜ','POLÍTICA DEL HOST','DESCUBRIMIENTO','ACTIVACIÓN','FRONTERA DELEGADA · CONTEXTO HIJO','CONTEXTO HIJO','HERRAMIENTAS FILTRADAS','WORKTREE · OPCIONAL','AUTORIDAD EXTERNA','HOOK PREVENTIVO','AUTORIZACIÓN','EFECTO EXTERNO','EVALUACIÓN · FRONTERAS INDEPENDIENTES','resultado + evidencia'],forbidden:['Package ≠ context ≠ authority','PLUGIN · DISTRIBUTION','PARENT CONTEXT','HOST POLICY','DELEGATED BOUNDARY','EXTERNAL AUTHORITY','PREVENTIVE HOOK','AUTHORIZATION','EXTERNAL EFFECT','EVALUATION · INDEPENDENT']},
 {locale:'en',route:'/en/series/context-engineering-memory-mcp/06-skills-plugins-subagents-hooks-context-isolation-evaluation/',required:['Package ≠ context ≠ authority','PLUGIN · DISTRIBUTION','SKILL','SUBAGENT DEFINITION','HOOK CONFIGURATION','PARENT CONTEXT Cₜ','HOST POLICY','DISCOVERY','ACTIVATION','DELEGATED BOUNDARY · CHILD CONTEXT','CHILD CONTEXT','FILTERED TOOLS','WORKTREE · OPTIONAL','EXTERNAL AUTHORITY','PREVENTIVE HOOK','AUTHORIZATION','EXTERNAL EFFECT','EVALUATION · INDEPENDENT BOUNDARIES','result + evidence'],forbidden:['Paquete ≠ contexto','DISTRIBUCIÓN','DEFINICIÓN SUBAGENTE','CONFIGURACIÓN HOOK','CONTEXTO PADRE','POLÍTICA DEL HOST','FRONTERA DELEGADA','AUTORIDAD EXTERNA','HOOK PREVENTIVO','EFECTO EXTERNO','FRONTERAS INDEPENDIENTES']},
];
const viewports=[{name:'desktop',width:1440,height:1000,hasTouch:false},{name:'mobile',width:390,height:844,hasTouch:true}];
const browser=await chromium.launch({headless:true});
try{
 for(const testCase of cases)for(const viewport of viewports){
  const context=await browser.newContext({viewport:{width:viewport.width,height:viewport.height},hasTouch:viewport.hasTouch,isMobile:viewport.hasTouch,reducedMotion:'reduce'});const page=await context.newPage();const runtimeErrors=[];const consoleErrors=[];
  page.on('pageerror',e=>runtimeErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});
  const response=await page.goto(`${base}${testCase.route}`,{waitUntil:'networkidle'});check(response?.ok(),`${testCase.route}: ${viewport.name} HTTP ${response?.status()??'no response'}`);
  const lang=await page.locator('html').getAttribute('lang');check((lang||'').toLowerCase().startsWith(testCase.locale),`${testCase.route}: ${viewport.name} wrong html lang ${lang}`);check(await page.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),`${testCase.route}: reduced-motion inactive`);
  const visual=page.locator('.s5v-context-extension-isolation');check((await visual.count())===1,`${testCase.route}: ${viewport.name} expected one chapter 3.6 visual`);
  if(await visual.count()){
   const label=(await visual.getAttribute('aria-label'))?.trim()||'';check(label.length>=75,`${testCase.route}: ${viewport.name} weak aria-label`);const text=(await visual.innerText()).toLowerCase();for(const t of testCase.required)check(text.includes(t.toLowerCase()),`${testCase.route}: ${viewport.name} missing ${JSON.stringify(t)}`);for(const t of testCase.forbidden)check(!text.includes(t.toLowerCase()),`${testCase.route}: ${viewport.name} untranslated ${JSON.stringify(t)}`);
   check((await visual.locator('.s5v-arch-map__pipe,.s5v__steps--tabs,[data-s5v-stepper],[data-s5v-tabs]').count())===0,`${testCase.route}: cosmetic/linear visual regression`);
   const g=await visual.evaluate(root=>{const box=s=>{const n=root.querySelector(s);if(!n)return null;const r=n.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height,cx:r.left+r.width/2,cy:r.top+r.height/2};};return{pkg:box('[data-boundary="package"]'),host:box('[data-boundary="host"]'),child:box('[data-boundary="child"]'),authority:box('[data-boundary="authority"]'),eval:box('[data-boundary="eval"]'),skill:box('[data-node="skill"]'),parent:box('[data-node="parent-context"]'),policy:box('[data-node="host-policy"]'),discovery:box('[data-node="discovery"]'),activation:box('[data-node="activation"]'),envelope:box('[data-node="delegation-envelope"]'),childContext:box('[data-node="child-context"]'),tools:box('[data-node="filtered-tools"]'),worktree:box('[data-node="worktree"]'),hook:box('[data-node="pre-hook"]'),auth:box('[data-node="integration-auth"]'),effect:box('[data-node="external-effect"]'),verify:box('[data-node="verify"]'),skillDiscovery:box('[data-edge="skill-discovery"]'),activationParent:box('[data-edge="activation-parent"]'),policyDelegate:box('[data-edge="policy-delegate"]'),childReturn:box('[data-edge="child-return"]'),policyHook:box('[data-edge="policy-hook"]'),hookAuth:box('[data-edge="hook-auth"]'),authEffect:box('[data-edge="auth-effect"]'),effectVerify:box('[data-edge="effect-verify"]'),evalActivation:box('[data-edge="eval-activation-edge"]'),evalIsolation:box('[data-edge="eval-isolation-edge"]'),evalHooks:box('[data-edge="eval-hooks-edge"]'),evalEffects:box('[data-edge="eval-effects-edge"]')};});
   for(const [n,b] of Object.entries(g))check(Boolean(b&&b.width>=0&&b.height>=0),`${testCase.route}: ${viewport.name} missing geometry ${n}`);
   if(g.pkg&&g.host&&g.authority&&g.eval){check(g.pkg.right<g.host.left+5,`${testCase.route}: package/host boundaries overlap`);check(g.host.right<g.authority.left+5,`${testCase.route}: host/authority boundaries overlap`);check(g.eval.top>Math.max(g.host.bottom,g.authority.bottom)+20,`${testCase.route}: evaluation lane collapsed into runtime topology`);}
   if(g.child&&g.host&&g.parent&&g.policy){check(g.child.left>=g.host.left&&g.child.right<=g.host.right,`${testCase.route}: child context escapes host boundary`);check(g.child.top>g.parent.bottom+100&&g.child.top>g.policy.bottom+100,`${testCase.route}: delegated boundary collapsed into parent context`);}
   if(g.skill&&g.discovery&&g.activation&&g.parent&&g.skillDiscovery&&g.activationParent){check(g.activation.cx>g.discovery.cx+120,`${testCase.route}: discovery→activation relation collapsed`);const packageGap=Math.max(1,g.discovery.left-g.skill.right);check(g.skillDiscovery.left<=g.skill.right+3&&g.skillDiscovery.right>=g.discovery.left-15&&g.skillDiscovery.width>packageGap*0.75&&g.skillDiscovery.height>Math.abs(g.discovery.cy-g.skill.cy)*0.55,`${testCase.route}: package→discovery path collapsed`);check(g.activationParent.height>40,`${testCase.route}: activation→parent context path collapsed`);}
   if(g.envelope&&g.childContext&&g.tools&&g.worktree&&g.policyDelegate&&g.childReturn){check(g.childContext.cx>g.envelope.cx+100,`${testCase.route}: delegation envelope→child relation collapsed`);check(Math.abs(g.tools.cy-g.worktree.cy)<12,`${testCase.route}: capability/workspace peers collapsed`);check(g.policyDelegate.height>170,`${testCase.route}: policy→delegation path collapsed`);check(g.childReturn.height>180,`${testCase.route}: child evidence handback collapsed`);}
   if(g.policy&&g.hook&&g.auth&&g.effect&&g.verify&&g.policyHook&&g.hookAuth&&g.authEffect&&g.effectVerify){check(g.hook.cx>g.policy.cx+250,`${testCase.route}: authority boundary lost`);check(g.auth.cy>g.hook.cy+90&&g.effect.cy>g.auth.cy+90&&g.verify.cy>g.effect.cy+60,`${testCase.route}: preventive→authorization→effect→verify order collapsed`);const authorityGap=Math.max(1,g.hook.left-g.policy.right);check(g.policyHook.left<=g.policy.right+3&&g.policyHook.right>=g.hook.left-10&&g.policyHook.width>authorityGap*0.7,`${testCase.route}: policy→hook crossing collapsed`);check(g.hookAuth.height>30&&g.authEffect.height>30&&g.effectVerify.height>15,`${testCase.route}: side-effect chain collapsed`);}
   if(g.evalActivation&&g.evalIsolation&&g.evalHooks&&g.evalEffects){check(g.evalActivation.height>20,`${testCase.route}: activation eval probe collapsed`);check(g.evalIsolation.height>90,`${testCase.route}: isolation eval probe collapsed`);check(g.evalHooks.height>300,`${testCase.route}: hook-order eval probe collapsed`);check(g.evalEffects.height>100,`${testCase.route}: effect verification eval probe collapsed`);}
   const scroller=visual.locator('.ei-scroll');check((await scroller.count())===1,`${testCase.route}: topology-preserving scroll region missing`);if(await scroller.count()){check((await scroller.getAttribute('tabindex'))==='0',`${testCase.route}: scroll region not focusable`);const state=await scroller.evaluate(node=>{const maxScroll=node.scrollWidth-node.clientWidth;node.scrollLeft=maxScroll;void node.offsetWidth;const stage=node.querySelector('.ei-stage')?.getBoundingClientRect();const r=node.getBoundingClientRect();return{maxScroll,actualScroll:node.scrollLeft,stageWidth:stage?.width??0,stageRight:stage?.right??0,scrollerRight:r.right};});if(viewport.name==='mobile'){check(state.maxScroll>450&&state.actualScroll>450,`${testCase.route}: mobile topology did not survive scroll ${JSON.stringify(state)}`);await scroller.screenshot({path:path.join(outDir,`context-engineering-ch6-${testCase.locale}-mobile-visual-end.png`),animations:'disabled'});}else{check(state.maxScroll<=1&&state.actualScroll<=1,`${testCase.route}: desktop clips horizontally ${JSON.stringify(state)}`);check(state.stageWidth>=900&&state.stageRight<=state.scrollerRight+1,`${testCase.route}: desktop stage escapes viewport ${JSON.stringify(state)}`);}await scroller.evaluate(node=>{node.scrollLeft=0;});}
   await visual.screenshot({path:path.join(outDir,`context-engineering-ch6-${testCase.locale}-${viewport.name}-visual.png`),animations:'disabled'});
  }
  const article=(await page.locator('main').innerText()).toLowerCase();const articleTerms=testCase.locale==='es'?['skill','plugin','subagente','hook','contexto','aislamiento','autorización','evaluación']:['skill','plugin','subagent','hook','context','isolation','authorization','evaluation'];for(const t of articleTerms)check(article.includes(t),`${testCase.route}: ${viewport.name} article missing ${t}`);const overflow=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth}));check(overflow.scrollWidth<=overflow.clientWidth+1,`${testCase.route}: ${viewport.name} page overflow ${JSON.stringify(overflow)}`);for(const e of runtimeErrors)failures.push(`${testCase.route}: ${viewport.name} runtime error: ${e}`);for(const e of consoleErrors.filter(x=>!/favicon|Failed to load resource.*404/i.test(x)))failures.push(`${testCase.route}: ${viewport.name} console error: ${e}`);await page.screenshot({path:path.join(outDir,`context-engineering-ch6-${testCase.locale}-${viewport.name}-page.png`),fullPage:true,animations:'disabled'});await context.close();
 }
}finally{await browser.close();}
if(failures.length){console.error(`Context engineering chapter 3.6 browser/accessibility QA failed (${failures.length}):`);for(const f of failures)console.error(`- ${f}`);process.exit(1);}console.log('Context engineering chapter 3.6 browser/accessibility QA PASS: packaging, skill activation, delegation/context isolation, hook/authorization/effect chain, independent eval probes, localization, reduced-motion and responsive geometry are valid.');
